### ISSUE TITLE
传承交大无法下载文件

### ISSUE THREAD

**Issue by Ucey285** [SJTU-Plus/sjtu-plus.github.io#49]
显示有账户有过期账单，请问怎么解决

**Comment by skyzh** [comment]
没有看懂您的问题。

**Comment by skyzh** [comment]
能否提供可以复现问题的链接？

**Comment by skyzh** [comment]
已确认传承交大的 BCE 对象存储欠费。传承交大的文件存储由前站长维护，我们无法直接处理。我们会尽快联系相关人员，解决这个问题。感谢您的支持。
